version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: stock-register-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=stock-register
    restart: unless-stopped

volumes:
  mongodb_data: 